# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base:     9333109c258fe53cf488c698be6f8223fd5115b7ced14721124994b4bb71f3e2d1c209b99dfc20f64e4db36954a3ab5045f344e2ba6f8bd74342cb0a308870c8
  encrypted_secret:    secret
  default_url_host:    <%= ENV["DEFAULT_URL_HOST"] %>

  allow_user_registration:     true
  allow_new_organization:      true
  allow_organization_upgrades: true

  twilio_sid:          <%= ENV["TWILIO_MASTER_ACCOUNT_SID"] %>
  twilio_token:        <%= ENV["TWILIO_MASTER_TOKEN"] %>
  twilio_application:  <%= ENV["TWILIO_APPLICATION"] %>

  freshbooks_endpoint: <%= ENV["FRESHBOOKS_API_ENDPOINT"] %>
  freshbooks_token:    <%= ENV["FRESHBOOKS_API_TOKEN"] %>

  google_key:          <%= ENV["GOOGLE_KEY"] %>
  google_token:        <%= ENV["GOOGLE_SECRET"] %>
  google_maps_key:     <%= ENV["GOOGLE_MAPS_KEY"] %>

test:
  secret_key_base:     01addf7b322e4b31258ce649e2f9b060a9f9f94ad5204f4c5ccc95fa13e6d476456ed3c92a7abbaafa11a258357bfb1618e94c3475258eedbd39310a57c27760
  encrypted_secret:    secret
  default_url_host:    <%= ENV["DEFAULT_URL_HOST"] %>

  allow_user_registration:     true
  allow_new_organization:      true
  allow_organization_upgrades: true

  twilio_sid:          <%= ENV["TWILIO_TEST_ACCOUNT_SID"] %>
  twilio_token:        <%= ENV["TWILIO_TEST_TOKEN"] %>
  twilio_application:  <%= ENV["TWILIO_APPLICATION"] %>

  freshbooks_endpoint: <%= ENV["FRESHBOOKS_API_ENDPOINT"] %>
  freshbooks_token:    <%= ENV["FRESHBOOKS_API_TOKEN"] %>

  google_key:          <%= ENV["GOOGLE_KEY"] %>
  google_token:        <%= ENV["GOOGLE_SECRET"] %>
  google_maps_key:     <%= ENV["GOOGLE_MAPS_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:     <%= ENV["SECRET_KEY_BASE"] %>
  encrypted_secret:    <%= ENV["ATTR_ENCRYPTED_SECRET"] %>
  default_url_host:    <%= ENV["DEFAULT_URL_HOST"] %>
  
  allow_user_registration:     false
  allow_new_organization:      false
  allow_organization_upgrades: false

  twilio_sid:          <%= ENV["TWILIO_MASTER_ACCOUNT_SID"] %>
  twilio_token:        <%= ENV["TWILIO_MASTER_TOKEN"] %>
  twilio_application:  <%= ENV["TWILIO_APPLICATION"] %>
  
  freshbooks_endpoint: <%= ENV["FRESHBOOKS_API_ENDPOINT"] %>
  freshbooks_token:    <%= ENV["FRESHBOOKS_API_TOKEN"] %>
  
  google_key:          <%= ENV["GOOGLE_KEY"] %>
  google_token:        <%= ENV["GOOGLE_SECRET"] %>
  google_maps_key:     <%= ENV["GOOGLE_MAPS_KEY"] %>
