require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PhoneBooksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PhoneBook. As you add validations to PhoneBook, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PhoneBooksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all phone_books as @phone_books" do
      phone_book = PhoneBook.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:phone_books)).to eq([phone_book])
    end
  end

  describe "GET show" do
    it "assigns the requested phone_book as @phone_book" do
      phone_book = PhoneBook.create! valid_attributes
      get :show, {:id => phone_book.to_param}, valid_session
      expect(assigns(:phone_book)).to eq(phone_book)
    end
  end

  describe "GET new" do
    it "assigns a new phone_book as @phone_book" do
      get :new, {}, valid_session
      expect(assigns(:phone_book)).to be_a_new(PhoneBook)
    end
  end

  describe "GET edit" do
    it "assigns the requested phone_book as @phone_book" do
      phone_book = PhoneBook.create! valid_attributes
      get :edit, {:id => phone_book.to_param}, valid_session
      expect(assigns(:phone_book)).to eq(phone_book)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PhoneBook" do
        expect {
          post :create, {:phone_book => valid_attributes}, valid_session
        }.to change(PhoneBook, :count).by(1)
      end

      it "assigns a newly created phone_book as @phone_book" do
        post :create, {:phone_book => valid_attributes}, valid_session
        expect(assigns(:phone_book)).to be_a(PhoneBook)
        expect(assigns(:phone_book)).to be_persisted
      end

      it "redirects to the created phone_book" do
        post :create, {:phone_book => valid_attributes}, valid_session
        expect(response).to redirect_to(PhoneBook.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved phone_book as @phone_book" do
        post :create, {:phone_book => invalid_attributes}, valid_session
        expect(assigns(:phone_book)).to be_a_new(PhoneBook)
      end

      it "re-renders the 'new' template" do
        post :create, {:phone_book => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested phone_book" do
        phone_book = PhoneBook.create! valid_attributes
        put :update, {:id => phone_book.to_param, :phone_book => new_attributes}, valid_session
        phone_book.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested phone_book as @phone_book" do
        phone_book = PhoneBook.create! valid_attributes
        put :update, {:id => phone_book.to_param, :phone_book => valid_attributes}, valid_session
        expect(assigns(:phone_book)).to eq(phone_book)
      end

      it "redirects to the phone_book" do
        phone_book = PhoneBook.create! valid_attributes
        put :update, {:id => phone_book.to_param, :phone_book => valid_attributes}, valid_session
        expect(response).to redirect_to(phone_book)
      end
    end

    describe "with invalid params" do
      it "assigns the phone_book as @phone_book" do
        phone_book = PhoneBook.create! valid_attributes
        put :update, {:id => phone_book.to_param, :phone_book => invalid_attributes}, valid_session
        expect(assigns(:phone_book)).to eq(phone_book)
      end

      it "re-renders the 'edit' template" do
        phone_book = PhoneBook.create! valid_attributes
        put :update, {:id => phone_book.to_param, :phone_book => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested phone_book" do
      phone_book = PhoneBook.create! valid_attributes
      expect {
        delete :destroy, {:id => phone_book.to_param}, valid_session
      }.to change(PhoneBook, :count).by(-1)
    end

    it "redirects to the phone_books list" do
      phone_book = PhoneBook.create! valid_attributes
      delete :destroy, {:id => phone_book.to_param}, valid_session
      expect(response).to redirect_to(phone_books_url)
    end
  end

end
